### ISSUE TITLE
Add a css file?

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#110]
I'm not sure if I like that idea or not, but let's have a discussion.
See #90 for the start of this.

The idea is to add a css file that could set the default styles to our elements based on classes.
This css file could also be split like our js files (per modules/components).

For example, we could apply `box-sizing: border-box` to all elements inside the root QML element this way.

Is it worth it? What would be the downsides of introducing a css file to the bundle?
/cc @qmlweb/collaborators.

**Comment by igosoft** [comment]
Separating style from business logic is always good idea. However I'm not sure if we need css file for it. Shouldn't we control a style from Javascript ?

**Comment by henrikrudstrom** [comment]
hmm, from a readablility perspective it would be nice if everything is defined in javascript, could we not use inheritance to set these properties?

**Comment by ChALkeR** [comment]
> could we not use inheritance to set these properties?

Perhaps we could, looks like a good idea to me.

**Comment by ChALkeR** [comment]
Approach like in #120 and setting everything from js based in iheritance instead of styles should work.
I'm closing this, if you have other opinions — feel free to reopen.
