### ISSUE TITLE
Broken merge by @igosoft?

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#111]
I removed those commits from master and placed them in a separate branch: [broken-merge-20160306](https://github.com/qmlweb/qmlweb/tree/broken-merge-20160306).

Those were not reviewed, the build was failing.

/cc @igosoft

**Comment by ChALkeR** [comment]
Just making sure that nothing is lost.

**Comment by igosoft** [comment]
Those changes have been done by me using github and those are the result of "bugs" in github. For example adding new file to selected branch finish with adding to master :).

**Comment by ChALkeR** [comment]
@igosoft If you can confirm that none of your commits is lost, we can close this =).

**Comment by igosoft** [comment]
I confirm. Those changes that you selected must be removed from master.

**Comment by ChALkeR** [comment]
@igosoft Thanks! I already removed them from master, those are kept in a separate branch: https://github.com/qmlweb/qmlweb/commits/broken-merge-20160306
