### ISSUE TITLE
Change license to MIT?

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#12]
Needs everyone's approval.
See #4.

**Comment by lpaimen** [comment]
While I don't see a lot difference between BSD and MIT, you have my approval.

**Comment by Plaristote** [comment]
I approve.

@lpaimen I stumbled uppon this: https://github.com/github/choosealicense.com/issues/257
If I got it right, it makes sense for qmlweb to allow people to not reproduce the license in their redistributions of qmlweb. I'm guessing minimized javascript might count as "binary".

**Comment by ChALkeR** [comment]
I have no strong preference of MIT over BSD, but our current BSD license is modified BSD-3-clause.

It should be noted that we currently depend on and bundle UglifyJS2, which is licensed under BSD-2-clause.

**Comment by ChALkeR** [comment]
Replaced by #52.
