### ISSUE TITLE
implement QtQuick.Test

### ISSUE THREAD

**Issue by henrikrudstrom** [qmlweb/qmlweb#130]
what if we implement [QtQuick Test](http://doc.qt.io/qt-5/qtquick-qtquicktest.html)?
A lot of the testing code needs to be in qml anyways.
Dont think it should be very hard to implement, did some experiments (see #106)
The big bonus is that we can run some of the suites in Qt to verify that they run (and generate screenshots). Once we start testing mouseclicks and focus or more complex issues, knowing that the test _should_ work could be nice...

**Comment by ChALkeR** [comment]
Yes, this would be a nice thing to have.

**Comment by ChALkeR** [comment]
Though the module is named just `QtTest` =).

**Comment by ChALkeR** [comment]
See #389

**Comment by ChALkeR** [comment]
Solved in #389, but more work should be done to get more methods implemented.
