### ISSUE TITLE
Use codecov.io instead of coveralls?

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#136]
Coveralls was not very convenvient — it mixed up coverage results for the master branch and for PRs for some reason, it was hard to understand what was going on with the coverage score without looking into each individual PR manually.

On top of that, coveralls is down now.

I will give https://codecov.io/ a try, perhaps.

**Comment by henrikrudstrom** [comment]
Think its worth a try, we can alwasy go back!
