### ISSUE TITLE
code duplications: lib/parser.js ~ uglify/parse.js

### ISSUE THREAD

**Issue by henrikrudstrom** [qmlweb/qmlweb#140]
The parser is currently a bit beyond me, there seems to be a *lot* of duplicate code or at least functions in `lib/parser.js` and `uglify/parse.js`. I suppose a lot of this can safely be removed

**Comment by Plaristote** [comment]
I took a look at this a few days ago. Those duplications should be removed indeed, but I don't think we can remove them safely yet.
One of the parser is involved with parsing javascript within QML files, while the other is used to parse javascript in JS files. I'm not yet entirely sure that one of the two parser could do both of those jobs by itself without some big changes.

**Comment by henrikrudstrom** [comment]
I see. is it uglify/parse.js that parses JS files?
Why are we parsing the javascript files? is it just to handle the additional import syntax?
`.import Qt.test 1.0 as JsQtTest`

**Comment by Plaristote** [comment]
From my perspective, we need to parse them to find out which symbols are to be made available from contexts.
For instance, if you wish to use an alias for a javascript file, you need to take everything from the global scope of the javascript file, and put it all in an object using the alias name.

**Comment by ChALkeR** [comment]
Fixed by #153.
