### ISSUE TITLE
Clean up folder structure

### ISSUE THREAD

**Issue by henrikrudstrom** [qmlweb/qmlweb#143]
The folder structure in `src/` seems a bit random. Would be nice to clean this up to anticipate splitting the repo into modules, #2 and make the structure a bit flatter.

1. `src/qmlweb/` --- is this used, should it be part of the core project? 

2. `src/helpers/` and `uglify`--- will probably be removed soon anyway.

3. `qml.js` / `UpdateGeometry.js` / `QML*.js` --- these map nicely to the [QDeclarative](http://doc.qt.io/qt-4.8/qtdeclarative-module.html)

4. `Component.js`/`Item.js`/`PropertyChanges.js` --- dont they belong in the QtQuick folder? or they could go together with the `QML*.js` as they are part of the 

5. `qtcore/qml/lib/*.js` --- this is mostly parsing. `import.js` should be considered in #126.

6. `qtcore/*.js` --- mostly constants, not so much code. not sure if this should have a dedicated folder or be grouped together with qml/qdeclarative (3.)

7. `qtcore/qml/elements/*` --- could be moved a bit up the hierarchy

Just an initial draft, 
```
src/
   parse/ --- (5.)
   qtcore/ --- (6.)
   declarative/ --- (3. / 4.) not sure about the name (could be qml or qdeclarative or engine...)
   elements/ --- (7.) could also be called `modules`
      QtQuick/
      QtQuick.Controls/
      ...
  
   
   


```

**Comment by Plaristote** [comment]
1. No, shouldn't be part of the core project.
However, the Settings object is supposed to be an implementation of [this](http://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html), but back in those days, property aliases didn't work as they should, so I didn't put it in the right module. 
So maybe we want this object to go somehwere else. The RestModel isn't something from QML and should be removed.

2. Fairly certain I got rid of them in the `browserified` branch, so yeah, it's gonna disappear.

6. I think it needs its own folder. Ideally, we would have a part of qmlweb that could be used without qml altogether (all the features re-implementing things from Qt, rather than QML), and that's where these things would be.
This includes things such as the Qt object and the list models.

7. Yes, although I think they should all go in separate modules. Even the most basic QtQuick imports should probably be a separate module.

**Comment by henrikrudstrom** [comment]
1. I see, persistent settings saved in xml or windows registry. would cookies be a good webqml analog?

3. "be used without qml altogether", Do you mean without any qml parsing related code?

4. `PropertyChanges` clearly belongs in qtquick. 
`Item` and `Component` is defined in the QtQuick module but also in QDeclarative. `Component` is integral to the engine and loading so i think it needs to be in `declarative` (3.). Not so sure about `Item`. 
Another alternative is to create two new objects: 
`QMLComponent` and `QMLItem` that live in `declarative` and inherit/redefine them in the `QtQuick` module.

**Comment by Plaristote** [comment]
1. Right now, it uses localStorage. Doing this properly with cookies would require adding a dependency, or writing a lot more code (cookies aren't as easy to use as localStorage).

3. That's what I meant yes.

4. Component should indeed be in 'declarative'. Item however involves DOM, and a few things that are specific to a browser environment, if I'm not mistaken. I'm not sure either about where it should end up.

**Comment by ChALkeR** [comment]
What's wrong with localStorage?

**Comment by ChALkeR** [comment]
localStorage seems to be more fit for this. cookies have stricter limitations and they add some data to each http request, which is clearly not wanted.

**Comment by henrikrudstrom** [comment]
nothing wrong with local storage, just didnt cross my mind at the time of writing...

**Comment by akreuzkamp** [comment]
A few random thoughts:
3. We shouldn't take inspiration from Qt4, imo, but rather from Qt5, so let's take inspiration from [QtQml](http://doc.qt.io/qt-5/qtqml-module.html)
3b. UpdateGeometry.js is QtQuick specific. Imo it belongs to QtQuick.
4. Quite some types in QmlWeb use Item as their base class although they should use QMLBaseObject instead. Item is only meant for graphical objects and as @Plaristote mentioned depends on DOM. Item is defined in QtQuick and as such definitely belongs there.

Summarizing the ideas you mentioned and bringing in my own ones, I'd propose:
```
src/
   qtcore/ --- only real QtCore stuff, i.e. QObject, Signal, ItemModels, etc.
   engine/ --- qml engine stuff, i.e. QMLEngine, AutoLoader, etc.
   engine/parse/ --- (or maybe just put the parser to engine?)
   modules/
      QtQml/ --- That is: QMLBaseObject, Binding, Connections, Timer as well as QMLInteger, etc.
      QtQuick/ --- Item definitely belongs here. UpdateGeometry also.
      QtQuick.Controls/
      QmlWebAddons/ --- This could be (1)
      ...
```
QMLProperty and Component could either go to QtQml or to engine.

**Comment by Plaristote** [comment]
I'm in full support of that for now. Although I think in the future, we should provide our modules using separate node package.

**Comment by ChALkeR** [comment]
Ok, my proposal:

 1. The main repository should only include qtcore and engine (without the parser).
 
 It will bundle to a file named `qmlweb.js` (or `qml.js`, or whatever else name we choose).
 2. Parser would be moved to a separate repository, [qmlweb-parser](/qmlweb/qmlweb-parser).
 
 See #173 for details on that.
 
 It will bundle to a file named `qmlweb.parser.js`.
 3. Modules would be moved to separate repositories:
 
  1. `qmlweb-module-qtquick` for `QtQuick` (bundled to `qmlweb.module.qtquick.js`),
  2. `qmlweb-module-qtquick-controls` for `QtQuick.Controls` (bundled to `qmlweb.module.qtquick.controls.js`),
  3. `qmlweb-module-qmlweb` for `QmlWeb` (bundled to `qmlweb.module.qmlweb.js`),
  4. `qmlweb-module-qmlweb-dom` for `QmlWeb.Dom` (bundled to `qmlweb.module.qmlweb.dom.js`),
 
 and so on.
 4. The crucial part of all this would be the autoloader. User will only load the `qmlweb.js` file, and all the other ones would be asynchronously loaded from the same path when needed. That would happen only for the known modules — the parser and everything that is named `Qt.*`, `QtQuick.*`, or `QmlWeb.*`. Parser (`qmlweb.parser.js`) would be loaded only when the user will try to load an unprocessed qml file.

**Comment by akreuzkamp** [comment]
Imo, splitting up the repository is worth another issue. The first step would be cleaning up the folder structure inside this repository, wouldn't it? Still your proposal sounds sensible to me :)

**Comment by ChALkeR** [comment]
@akreuzkamp, @henrikrudstrom I moved element definitions to `src/modules`.

**Comment by ChALkeR** [comment]
@akreuzkamp Re: https://github.com/qmlweb/qmlweb/issues/143#issuecomment-206811370, could you split those files currently in `src/qtcore` into `src/engine` and `src/qtcore`? I am not exactly sure about some of those.

**Comment by akreuzkamp** [comment]
@ChALkeR See #269. :)

**Comment by ChALkeR** [comment]
@akreuzkamp Is there anything else that should be done here, or does that look good enough?

**Comment by ChALkeR** [comment]
I believe this is now fixed. Anyone, free to reopen and/or comment if you think otherwise.
