### ISSUE TITLE
view rendered image from rendertest

### ISSUE THREAD

**Issue by henrikrudstrom** [qmlweb/qmlweb#144]
Is there any way save the images generated by the render test in phantomjs to a temporary folder. Would be useful to see what is actually rendered when a test fail.
@ChALkeR ?

**Comment by ChALkeR** [comment]
It's already supported =).
Perhaps it should be documented somewhere.

Just run `QMLWEB_SAVE_RENDER=1 npm test`, and the rendered results would be saved to `./tmp/render/` directory.

**Comment by ChALkeR** [comment]
See https://github.com/qmlweb/qmlweb/blob/master/tests/phantom.callback.js#L6-L7

**Comment by henrikrudstrom** [comment]
That makes life easier, thanks
