### ISSUE TITLE
If I want to participate in the development of writing specifications which need to follow

### ISSUE THREAD

**Issue by Gaubee** [qmlweb/qmlweb#151]
Hello , I recently learned QML this language , doing a simple to learn and use, very fond of QML language. My main technical direction is JavaScript. I very much hope to be able to participate in the development of qmlweb this project , as compared to the current front-end framework features , QML is undoubtedly more competitive with perfection .
 I have FORK project , ready to be developed , but I do not understand the current team to develop some grammatical norms , if I want to participate in the development , which needs to be done to follow the grammar and style code format specification ?

**Comment by Plaristote** [comment]
We haven't decided on any grammatical norms, as we are still merging the works of several of us contributors, and we ourselves haven't used the same norms in our respective forks.

For now, as long as `npm run lint` passes without errors, it's ok with me. We might open an issue later before deciding on a specific code style, though I think this should wait until we have finished merging the other contributors' forks (as, if I'm not mistaken, these kind of rules will be enforced by the linter, and we don't want the linter to show errors while we're just merging old commits).
