### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by ElderOrb** [qmlweb/qmlweb#154]
First of all, I really glad to see the project was resumed and progressing fast enough last couple months! Keep up great work guys!

But is there any docs available with a list of what supported and what not ? 

At the moment it is only clear that 'Rectangle' component is supported, but this is a bit not enough :)

**Comment by ChALkeR** [comment]
@ElderOrb This is still in the early stage merging all the forks.

Documentation would come after that and some refactoring, I guess. Targeting for v1.0.0 for now.

My opinion is that we should include the primary documentation to the repo itself, not to the wiki — it would be easier to keep it in sync that way, also it's forkable and easier to consume (e.g. in archive or on site).

Though the wiki could have some internali-ish notes.

**Comment by ChALkeR** [comment]
> But is there any docs available with a list of what supported and what not ?
>
> At the moment it is only clear that 'Rectangle' component is supported, but this is a bit not enough :)

I created https://github.com/qmlweb/qmlweb/projects/1 for that. It's not yet filled with all the data, but that is where the current status of things would be kept for now.

The API documentation is being worked on in the https://github.com/qmlweb/qmlweb/tree/master/docs folder.

I don't see anything more to discuss on this issue or any specific things that should be done here (except for populating the project mentioned above), so I'm closing this. Feel free to continue the discussion, though =).
