### ISSUE TITLE
igosoft-patches and fork-arnopaehler branches relation

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#158]
@igosoft, @arnopaehler 

These two files look exactly the same:
 * [igosoft-patches/src/qtcore/qml/elements/QtQuick.Window/Screen.js](https://github.com/qmlweb/qmlweb/blob/igosoft-patches/src/qtcore/qml/elements/QtQuick.Window/Screen.js)
 * [fork-arnopaehler/src/qtcore/qml/elements/QtQuick.Window/Screen.js](https://github.com/qmlweb/qmlweb/blob/fork-arnopaehler/src/qtcore/qml/elements/QtQuick.Window/Screen.js)

The relation between those branches is not reflected in the commit history. Could any of you please clear things up a bit? That would help merging those.

Ref: #62, #17.

**Comment by igosoft** [comment]
@ChALkeR please use/merge arnopaehler verion

**Comment by ChALkeR** [comment]
@igosoft Thanks!

I guess that we should merge changes from fork-arnopaehler first, then.

**Comment by igosoft** [comment]
Yes.
5 kwi 2016 01:24 "Сковорода Никита Андреевич" <notifications@github.com>
napisał(a):
