### ISSUE TITLE
Merge fork-labsin

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#16]
Merge fork by @labsin.

- [x] 7080bd5 Fix gulpfile to do qt task before qt.min — **Merged**
- [x] 46ad080 Remove libs from repo — **Rejected,** libs will be kept in the repo for bower.
- [ ] f7b9791 Fix component context
- [ ] daea9af Resemble more like qt5 modules
- [ ] d5d7248 Implement QMLColor
- [ ] 1c200b2 Change QMLProperty value constructor to object
- [x] 0be9fc1 Fix nodejs with uglify2 in browser — **Rejected**, this will be redone in a better way.
- [x] 8f80b5a Fix pre-parse example including qt.js and qt.min.js — **Rejected**, should go into gulp-qmlweb, that would be rewritten.
- [x] 432f462 Fix nodejs with uglify2 — **Rejected**, this will be redone in a better way.

**Comment by labsin** [comment]
Mostly unfinished.

**Comment by ChALkeR** [comment]
@labsin Is there a reason for closing this? I have not reviewed it, but te QMLColor changes looked promising.

**Comment by labsin** [comment]
I think I'll redo it ones the merges are in.
Op 24 feb. 2016 20:44 schreef "Сковорода Никита Андреевич" <
notifications@github.com>:

**Comment by ChALkeR** [comment]
@labsin Ah, as you wish! =)

**Comment by henrikrudstrom** [comment]
@labsin, @ChALkeR i like the look of the QMLComponent class in f7b97915a8e4cb79c39dda5bd55b6fc6b56f9973, takes away a lot of work from qmlEngine. is it working?
