### ISSUE TITLE
Merge fork-arnopaehler

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#17]
Merge fork by @arnopaehler.

- [ ] c839ec4 more reformatting in QtQuick.Controls, modifications in Screen.js
- [ ] dcda2c3 edit QtQuick.Controls items for standardized code layout add .Coffeescript files for eqch of the item files
- [ ] b83f5ae several Items mods; fix Screen.js; update Widgets.qml
- [ ] 81dba7f clean up, simplify and reformat several QML items add QMLScreen.js and enums to qt.js
- [ ] d4baf53 fixes in parser.js and ComboBox.js changes in CanvasX and LoaderX tests
- [x] 855c7fd edit Demo, LoaderX and Widgets tests LoaderX now uses ComboBox to present a selection of test QMLs to load — **Rejected,** examples are not wanted here, they would be collected in a separate repo.
- [ ] 201e20d fix parser.js / qml.js to parse array, num and string correctly update Combo.js
- [ ] 4086cb0 move Button.js to QtQuick.Controls where it belongs add ComboBox.js and a test for it in Widgets.qml (work in progress)
- [ ] 4627a6d extensive renaming and editing of test examples add Demo.qml that includes and displays all other examples add HowTo.md with usage tips — there are some actual changes here, perhaps needs splitting.
- [x] bf4082c change overflow = hidden to overflow = auto in Item.js cosmetic changes in Fontloader.js cleanup Widgets.qml — **Rejected**, contrary to what the commit message says, this commit only changes a visual test (which is unwanted in this repo).
- [x] 101db47 add options parameter to Loader.js extend Loader test example add sample text file ZZ.Z for Loader testing — **Merged** (the main part of it, without examples).
- [x] 073f526 some small fixes; start implementing QMLLoader adding test example Loader.qml — **Merged** (the main part of it, without examples).
- [x] ffa6fc9 fix Repeater.js create PlaanetsModel.qml and update ListView and ColumnRow tests — **Rejected**, code style changes (those would be catched by lint after merge) plus visual tests (those are not wanted in this repo).
- [x] 16ebcc1 minor repairs — **Rejected**, these look like they actually break some code.
- [x] 9309753 eliminate Undefined and replace references with undefined — **Merged** in #113.
- [x] fd864fb fix a typo in process.js that escape eslint add a samll Windows Power Shell script to run eslint recursively — **Rejected**, this is actually a fixup of a mistype introduced in a previous commit, which is also rejected.
- [x] 2aa28d1 check JS with eslint, see .eslintrc for the specifications — **Rejected**, this will be re-done after merges, with a different eslint rules set.
- [x] 0a59357 another day another commit maybe now committed as intended — **Rejected**, this is just a fixup of the previous commit which is rejected, plus a new visual test (those are not wanted).
- [x] b98ce9a more documentation/comments cleanup — **Rejected**, this one just removes comments, leaves some of leftovers and breaks the build, also removes `Object.create` polyfill which is restored by the follow-up commits (and is not there anyway on the master branch).
- [x] faaaba5 extensive documentation changes code rearrangement in JS — **Rejected**, no actual code changes, controversial documentation refactoring.
- [x] 9e65ecc tests: extract the ListModel from ListView and "include" it as CitiesModel in ListView tests: cleanup ListView — **Rejected**, visual tests are not wanted in this repo.
- [x] 3ada0bf edit gulpofile.js to add gulp-changed (plus a local utility task) minor rearrangement in qt.[min.]js in lib (no code changes) minor change in ListView in tests (ListView does not display correctly in Windows 10 Edge) — **Rejected**, the gulpfile change was reverted later, visual tests are not wanted in this repo.
- [x] 8a45171 minor changes in Text and ListView in tests — **Rejected**, only visual tests are changed.
- [ ] 9b86ec7 reformat and cleanup  Generic.js,, TestPlugin.js, Text.js and TextEdit.js — actually, not sure. Changes in classes introduced in this branch should probably be merged or sqashed.
- [x] 6212a39 add a missing semicolon in TestPlugin.js — **Rejected,** syntax changes are unwanted, eslint will solve this later.
- [x] f6ba02e and one more — **Rejected,** this is just a status list that would be surely broken by the merge and unsupported.
- [ ] e6aec16 added files omitted in last commit -- refactored here
- [ ] 3647358 see README.md for details -- refactored here
- [x] 71786c8 code additions and rearrangements lib/qt.js add Title.qml to tests and use in all tests examples toprovide a top level title — **Rejected**, built code and tests only, sources included in a later commit.
- [x] 125f6ea extend TextEdit further — **Rejected**, built code and tests only, sources included in a later commit.
- [x] b95f74a qt.js : let TextEdit modify CSS as is possible in Text (work in progress) tests: modified TextEdit and Widgets — **Rejected**, built code and tests only, sources included in a later commit.
- [x] ef27864 add some font features wo TextEdit in Widgets in tests — **Rejected**, tests only.
- [x] 202ed09 add font functionality to TextEdit in qt.js modify TextEdit in tests to demonstrate font functionality — **Rejected**, built code and tests only, sources included in a later commit.
- [x] 22c72ea changes to TextEdit in tests modified TextEdit in qt.js — **Rejected**, built code and tests only, sources included in a later commit.
- [x] ac735f5 start adding QMLTextEdit to qt.js add TextEdit to tests modified ColumnRow and Widgets in tests — **Rejected**, built code and tests only, sources included in a later commit.
- [x] b074543 add ColumnRow example — **Rejected,** examples are not wanted here.
- [x] 3646a0a add additional tests examples accidentally not included in latest commit — **Rejected,** examples are not wanted here.
- [x] c0fe4d9 add TestPlugin toqt.js add more tests examples — **Rejected,** examples are not wanted here.
- [x] 4617ec4 no message — **Rejected**, examples only.
- [x] e20834e no message — **Merged** in #23.
- [x] 4e26e05 no message — **Rejected**, README change special to that fork.
- [x] e4f6de9 add QMLFont constructor in Checkbox and TextArea change permitted versions in TextArea add QMLAnimation constructor in SequentialAnimation add more test examples as subdirectoy tests modify README.md — **Rejected**, built code only, sources included in a later commit.

**Comment by Plaristote** [comment]
I could start sorting this out if that's ok. I've already had a look.
There's some coffeescript in there. I'm not sure mixing javascript and coffeescript really is worth it, but if we chose to do it, we'll have to use gulp-coffee.

**Comment by ChALkeR** [comment]
I would prefer not to pull in coffeescript and keep everything written in js.

es6 would be good, though, and I plan using babel to transplit things, but before that we should merge what we can (increasing code differences would make it harder) and then clean things up.

**Comment by Plaristote** [comment]
Sounds good.

I started #23, it should take care of the 4617ec4, e20834e, 4e26e05 and e4f6de9 commit.
* 4617ec4 contains examples, and 4e26e05 makes a change to the readme that's irrelevant now. We can reject them.
* e4f6de9 only changes the compiled javascript.
* e20834e is merged in the pull request, with the updated compiled javascript.

**Comment by Plaristote** [comment]
In 3647358, there's a polyfill for the bind function. If we can all agree with that, I think it would be better not to implement polyfills in qmlweb's code.
Compatibility with older browsers should be the job of libraries such as Modernizr, that qmlweb's users can include to their project if they are concerned with older browser support.

**Comment by ChALkeR** [comment]
> In 3647358, there's a polyfill for the bind function.

That polyfill was actually introduced in 551f92cc and removed in f33d663710690a78900b014ea2f437c56a31bedf, I agree that we definitely don't need it in the qmlweb itself.

I'm not sure if we should do anything with 3647358 — it basically moves code around and cleans up things. Moving code around atm is undesired (until everything else is merged), minor cleanups were already made, tests are fixed in #25. Are there any actual changes in the `src/` folder that are not related to codestyle in that commit?

**Comment by ChALkeR** [comment]
> I started #23, it should take care of the 4617ec4, e20834e, 4e26e05 and e4f6de9 commit.

Great, thanks! Will take a look now.

**Comment by Plaristote** [comment]
I agree about 3647358, merging it would only make further merge harder. I've taken a look, and I can confirm than apart from codestyle changes, it only adds file that we wouldn't want in this repository anyway, and removes files that have already been moved in master. We shouldn't merge it.

**Comment by henrikrudstrom** [comment]
checked off some commits i believe are only related to code style and documentation, 
uncheck them if you disagree.

**Comment by henrikrudstrom** [comment]
We dont want the widget and screen class right?

**Comment by henrikrudstrom** [comment]
We could consider the TextEdit although its very incomplete. 
201e20ddd4ba463bcfc3d4aa5b8f0c070443d568 might be something?

There is a ComboBox implementation, QtQuick.Controls should be a different package i think.
there is also one here: also from @pavelvasev [here](https://github.com/pavelvasev/qmlweb.components)

**Comment by ChALkeR** [comment]
@henrikrudstrom 
> There is no diff for issue texts, so could you also leave a comment text time, please? I see which ones you did check, though, but

There is no diff for issue texts, so could you also leave a comment text time, please? I see which ones you did check, though, and it should be fine this time.

**Comment by ChALkeR** [comment]
@henrikrudstrom I do not agree with some of these, btw.
The problem is that these are unsorted and blended — some of the commits that mostly reorder code also change classes that were newly added in this branch. Most probably I will have to split these commits into sub-commits.

**Comment by ChALkeR** [comment]
@henrikrudstrom 
> We dont want the widget and screen class right?
Actually, why not? But we need to either choose one of implementations from various branches or merge them.

**Comment by ChALkeR** [comment]
@henrikrudstrom Thanks for the help here, btw!

**Comment by henrikrudstrom** [comment]
@ChALkeR was late last night: The widget class is actually an example, and yeah, the screen class we should keep.

**Comment by henrikrudstrom** [comment]
Compared fork-arnophaeler to master, 
here are some notable changes, but i dont think any of this be added
[QMLBinding.js]
(https://github.com/qmlweb/qmlweb/compare/fork-arnopaehler...master#diff-85f60202ce59275eb9c8add440cc126cL25)

[Component.js]
(https://github.com/qmlweb/qmlweb/compare/fork-arnopaehler...master#diff-85f60202ce59275eb9c8add440cc126cL25)

[parser.js]
(https://github.com/qmlweb/qmlweb/compare/fork-arnopaehler...master#diff-85f60202ce59275eb9c8add440cc126cL25)

not sure how accurate githubs compare function is, QtWindow/Screen.js was not shown in the diff for example...

**Comment by ChALkeR** [comment]
Ok. The leftover commits largely have invalid comment messages and are mixed up.
Perhaps I would just squash those and split again, like I'm doing with @igosoft patches.

**Comment by ChALkeR** [comment]
Ok. The leftover commits here mostly have invalid commit messages and are mixed up.
Perhaps I would just squash those and split again, like I'm doing with @igosoft patches.

**Comment by Plaristote** [comment]
I just took a look at this one:

> faaaba5 extensive documentation changes code rearrangement in JS — there are some actual code changes here, most probably this has to be split.

I haven't seen any code changes: the biggest visible change I've seen is a modified console.log message. Anything else is just fixing indentation and moving code around. Not sure this is the kind of thing we want to merge, since eslint will help us do this kind of stuff in the future.

**Comment by ChALkeR** [comment]
@Plaristote Thanks, it looks like you are correct and I was mistaken — there are no actual changes in faaaba5, just moving code around.

I don't think that we should merge documentation refactoring now, especially at the current state of master and this documentation. Note how it removes some important comments from function bodies.

We could redo the documentation later, and perhaps we could take a look at these changes when doing so, but I really doubt that someone would wish to take this commit and make it ready for merging on master.

**Comment by Plaristote** [comment]
201e20d: most of the changes are made on stuff that were removed from master.
Another change is the walkfixer, which adds code that works around missing walkers (num, array and string). However, these walkers have been added in master. I'm pretty sure walkfixer, and what it becomes in further commits (walk1), shouldn't be merged.
From that commit, only one change seems to be mergeable: the addition of "array" to the constructors object.

d4baf53: same here, it changes stuff from 201e20d, imo there's nothing to merge from this commit.

I've also looked at 4086cb0, there's indeed a few things to merge (I see at least tree commits emerging from this, one for adding the Canvas item, one for the gulpfile update, one for the Loader item update, although I'll have to first understand what the last two are actually doing before I merge those).

**Comment by ChALkeR** [comment]
Ok, updated list:  9b86ec7, e6aec16, 3647358, bbf3517.

I squashed the top few commits into bbf3517, see the [fork-arnopaehler-reordered](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-reordered) branch.

**Comment by ChALkeR** [comment]
Ok, I squashed everything left here into two commits: 8f08b35 and a8427a2.

8f08b35 contains 9b86ec7, e6aec16, 3647358 minus some surely unwanted changes, see the  [fork-arnopaehler-9b86ec7-reordered](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-9b86ec7-reordered) branch (its head is even with 9b86ec7).

a8427a2 contains  c839ec4, dcda2c3, b83f5ae, 81dba7f, d4baf53, 855c7fd, 201e20d, 4086cb0, 4627a6d  minus some surely unwanted changes, see the  [fork-arnopaehler-reordered](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-reordered) branch (its head is even with  c839ec4).

**Comment by ChALkeR** [comment]
The next step would be to split those two and move the style changes out of those. Will do that a bit later.

**Comment by ChALkeR** [comment]
To check current status, see the top commits at  [fork-arnopaehler-reordered](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-reordered) and [fork-arnopaehler-9b86ec7-reordered](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-9b86ec7-reordered) branch (its head is even with 9b86ec7) branches (the ones edited by me).

**Comment by ChALkeR** [comment]
I will clean this up a bit, removing unwanted changes, and then we can discuss what would be left here.

**Comment by ChALkeR** [comment]
Ok, the actual changes that were not yet applied or rejected are at 92eb17dc1248a1c2e263b49f0e3dfcb5754a895c and 6830c351056f16cc4f9a57060e7a1ced7964d846 now.

I'm going to squash those two now, the next step would be to split those into individual patches.

**Comment by ChALkeR** [comment]
First set of patches (92eb17d split): [fork-arnopaehler-patches1](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-patches1).
Commits:
 * 5252956 — Implement logCss() function
 * a712120 — Implement TextEdit
 * 5feb0bb — Implement TestPlugin
 * 79c6678 — .gitignore: Add .idea/ and /.project

**Comment by ChALkeR** [comment]
Second set of patches (6830c351056f16cc4f9a57060e7a1ced7964d846 split):  [fork-arnopaehler-patches2](https://github.com/qmlweb/qmlweb/commits/fork-arnopaehler-patches2).
Commits:
 * 2585cb5 Row: register effectiveLayoutDirection
 * fb6cd39 Add Qt.Align* constants
 * e7e6523 Implement Screen
 * 384b250 parser: walker updates
 * 0a09a8c More work on Loader
 * 41f545e A clarification of a TODO comment
 * ba8b9ff Register Array as 'array' basic QML type
 * 8fe2ad9 Implement TextField
 * 79e6124 TextArea: use strict comarison in updateValue
 * 1bded10 Implement objItems() and typeName()
 * e7cee0d Default to 'Object List' in objList() title argument
 * 36f6b2b SequentialAnimation: remove debug, remove descr() debug function
 * 501a197 Implement ComboBox
 * 3b9fe97 Item: use overflow: auto istead of overflow: hidden
 * 954894b QMLEngine: directly assign e.keypad in keyCodeToQt(e)
 * 43bccf8 Move Button to QtQuick.Controls
 * 55bd5e8 Implement Canvas
 * 8cdd241 [ignore] Remove a Canvas TODO stub
 * c9def86 Add a test signal to TestPlugin

**Comment by ChALkeR** [comment]
Closing in favor of #163. Everything not yet merged or rejected from here should be present there.
