### ISSUE TITLE
Merge fork-henrikrudstrom

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#18]
Merge fork by @henrikrudstrom.

- [ ] 159b493 ...

**Comment by ChALkeR** [comment]
@henrikrudstrom, `.gitignore` and `index.html` changes are not applicable now (and not needed).
Could you comment on the QMLEngine.js changes?

**Comment by henrikrudstrom** [comment]
this is not worth merging...

**Comment by henrikrudstrom** [comment]
the QMLEngine change: got a undefined object error somewhere.. but its probably changed by now...

**Comment by ChALkeR** [comment]
Ok, thanks.
