### ISSUE TITLE
Notice: contributors activity and PR review process

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#230]
/cc @qmlweb/collaborators, @qmlweb/core.

Given the current situation with PR review, I am going to land less important and less controversial changes directly on `master` for the time being.

I will still open PRs for merges of other peoples' code and for changes that are controversial, or where I would want to double-check that things are ok.

This issue will be open until the activity will rise again =).

**Comment by ChALkeR** [comment]
Closing this notice and posponing the issue until we will have more active contributors.

**Comment by machinekoder** [comment]
@ChALkeR It is still useful to create PRs, even if you merge them without further public reviewing. So the procedure stays the same when there are more active contributors and you get useful CI results before merging into the master branch.
