### ISSUE TITLE
How to correct use this js library 

### ISSUE THREAD

**Issue by toby20130333** [qmlweb/qmlweb#240]
follow this readme 
I run a nodejs server and open this url localhost:3000 to show some html page
but I get the following warning and no effect

> Synchronous`XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/

by the way:those qml and js can be loaded

`<!DOCTYPE html>
<html>
  <head>
    <title>QML Auto-load Example</title>
  </head>
  <body style="margin: 0;" data-qml="./qml/main.qml">
    <script type="text/javascript" src="./qmlweb/lib/qt.js"></script>
  </body>
</html>
`
nodejs code:
`
var http = require("http"),
    url = require("url"),
    path = require("path"),
    fs = require("fs"),
    port = process.argv[2] || 8888;

http.createServer(function(request, response) {

  var uri = url.parse(request.url).pathname
    , filename = path.join(process.cwd(), uri);

  fs.exists(filename, function(exists) {
    if(!exists) {
      response.writeHead(404, {"Content-Type": "text/plain"});
      response.write("404 Not Found\n");
      response.end();
      return;
    }

```
if (fs.statSync(filename).isDirectory()) filename += '/qtquick.html';

fs.readFile(filename, "binary", function(err, file) {
  if(err) {        
    response.writeHead(500, {"Content-Type": "text/plain"});
    response.write(err + "\n");
    response.end();
    return;
  }

  response.writeHead(200);
  response.write(file, "binary");
  response.end();
});
```

  });
}).listen(parseInt(port, 10));

console.log("Static file server running at\n  => http://localhost:" + port + "/\nCTRL + C to shutdown");
`

**Comment by stephenmdangelo** [comment]
That warning is benign. I don't know much about nodejs, but can you post your main.qml as well? I assume the node stuff is working if the XHR request is successfully fetching the main.qml.

**Comment by toby20130333** [comment]
@stephenmdangelo Hi What's Qt Version to Support this lib?Thanks

**Comment by toby20130333** [comment]
@stephenmdangelo can you send me a whole example to show how to use it?thank you!

**Comment by toby20130333** [comment]
@stephenmdangelo I get the follow output in chrome console:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
qmlstructure.js:251 Loading parser...
QMLEngine.js:79 Loading file [ qml/main.qml ]
```
but tha page has nothing to be show

**Comment by Plaristote** [comment]
Could you maybe make a gist with the code you're using ?

If you're not getting any error, this has to be a bug.

**Comment by ChALkeR** [comment]
@toby20130333 The output you are getting in the console is fine, but nothing displayed on the page is not.

Could you share your testcase, please?

**Comment by toby20130333** [comment]
my testcase is on the top of this issue,Please check it thanks

**Comment by Plaristote** [comment]
The http server you're using shouldn't be relevant to the issue, it should work with any http server (I use the `http-server` package).

For the record, I can't use the lib anymore. There's been a few changes with the new qmlweb-parser package, and as far as I can tell, loading qml file on runtime is currently broken. Though the problem I have has nothing to do with the problem you had, it's something new.

Anyway, loading qml files at runtime isn't the best way to use qmlweb, imho. I recommend using a Gulpfile, with the `gulp-qmlweb` package, to package your application in a single javascript file.

**Comment by ChALkeR** [comment]
@Plaristote 
> as far as I can tell, loading qml file on runtime is currently broken.

Is it? It works for me. Also, tests load files on runtime. What exactly is broken?

**Comment by toby20130333** [comment]
@Plaristote @ChALkeR 
Thanks,But i use npm install this qmlweb package not gulpfile,so i will be to use gulpfile to try it.

**Comment by Plaristote** [comment]
@ChALkeR My bad, it doesn't seem broken.
I was confused, because qmlweb-parser, as a package, is a dependency to qmlweb, but it doesn't look like we're actually using it.

From what I understood, the process is to clone qmlweb-parser and build it separately, then include the qmlweb.parser.js file in the `lib` folder (or have the two libs folders link to the same directory). We should probably explain that somewhere (and maybe put a link to the explanation in the exception, so that people trying to load qml files on runtime know why the qmlweb.parser.js file is missing for them).

**Comment by ChALkeR** [comment]
@Plaristote We are using it, there is no parser in this repo anymore.

`qmlweb-parser` is a `devDependency` for `qmlweb`: https://github.com/qmlweb/qmlweb/blob/master/package.json#L28 — that means that it's installed only for developent of `qmlweb` itself, but not installed as a package when someone depends on `qmlweb`.

At the build stage here, `qmlweb-parser` library is copied to the `dist` folder — so `qmlweb` package on npm and Bower bundle `qmlweb-parser` inside them:
```
node_modules/qmlweb/lib/
├── LICENSE
├── qmlweb.parser.js
├── qmlweb.parser.js.map
├── qmlweb.parser.min.js
├── qmlweb.parser.min.js.map
├── qt.js
├── qt.js.map
├── qt.min.js
└── qt.min.js.map
```

Parser is a separate file (`qmlweb.parser.min.js`), and it only gets loaded when there is need to parse a file that wasn't found in qrc.

**Comment by JoshuaKolden** [comment]
I'm not understanding this workflow either.  @Plaristote can you explain how one would use gulp-qmlweb to package QML to javascript?  As it works now for me I end up with a `qrc.js`, which defines qrc['qml/main.qml']  = [..]

However, the browser fails to render the main.qml file with an error:

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.qml, line 0)`

It says it's looking for `http://localhost:3000/qml/main.qml`

I'm using basically the same html as in the Readme:

```html
<html>
<head>
  <title>QML test</title>

  <!--build:css css/styles.min.css-->
  <link rel="stylesheet" href="css/styles.css">
  <!--endbuild-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

</head>
  <body style="margin: 0;" data-qml="qml/main.qml">
    Not working, this is still html world.

    <!--build:js js/main.min.js -->>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/qrc.js"></script>
    <!-- endbuild -->
    <script type="text/javascript" src="lib/qt.js"></script>
  </body>
</html>
```

I tried removing the `data-qml`, but that doesn't really make sense.  On top of this even when I get it working by letting it see both `qrc.js` and `main.qml`.  Some things are broken.  For example I can't use `TextField` from QtQuick.Controls.  

So how does one static, or dynamic qml rendering?  If I can get it working then I'd be happy to improve the documentation.

**Comment by Plaristote** [comment]
@JoshuaKolden It sounds like you are including the qmlweb library after the qrc file ? It should be the other way around. The qrc object is defined within lib/qt.js. That definition would override the qrc variable as it was declared in js/qrc.js.

We'll have to see the specifics for the things that would be broken.

**Comment by ChALkeR** [comment]
@JoshuaKolden, @Plaristote, @toby20130333

I added some examples to the Readme and to the [/examples](https://github.com/qmlweb/qmlweb/tree/master/examples) directory.

Note that the Web Components version is only supported in the latest master, not v0.2.0.

I believe that the issue here is resolved, so I'm closing this. If anyone doesn't think so or more basic issues arise — feel free to continue the discussion and/or reopen the issue.
