### ISSUE TITLE
Modules definition syntax.

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#260]
Atm, we have mixed modules definition syntax.
 1. [Animation](https://github.com/qmlweb/qmlweb/blob/master/src/modules/QtQuick/Animation.js) uses:
 ```js
  function QMLAnimation(meta) {
      callSuper(this, meta);
      …
  }

  registerQmlType({
    module:   'QtQuick',
    name:     'Animation',
    versions: /.*/,
    baseClass: 'QtQml.QtObject',
    constructor: QMLAnimation
  })
```
 2. [Column](https://github.com/qmlweb/qmlweb/blob/master/src/modules/QtQuick/Column.js) uses:
 ```js
  function QMLColumn(meta) {
      callSuper(this, meta);
  }

  QMLColumn.prototype.layoutChildren = function() {
      …
  }

  registerQmlType({
    module: 'QtQuick',
    name:   'Column',
    versions: /.*/,
    baseClass: 'Positioner',
    constructor: QMLColumn
  });
```
 3. [ListView](https://github.com/qmlweb/qmlweb/blob/master/src/modules/QtQuick/ListView.js) uses:
 
  ```js
  registerQmlType({
    module:   'QtQuick',
    name:     'ListView',
    versions: /.*/,
    baseClass: 'Repeater',
    constructor: function QMLListView(meta) {
      callSuper(this, meta);
      …
    } 
  });
```

We should decide on one format and convert all modules to use that single format.

**Comment by ChALkeR** [comment]
Atm, `registerQmlType` should be on the top — it includes the module name and some important properties (e.g. since 613ca9d0dfd4313c0f6fa248f4538dd09ec81bc7...061230729c9aae23f5c761811a29c8590c7f786e — the properties list).

Prototype functions could be defined after calling `registerQmlType` (that is supported), but I don't see a reason to do that. Also, I don't even see a reason for naming classes.

My proposal here is:
```js
registerQmlType({
  module: 'QtQuick',
  name:   'Column',
  versions: /.*/,
  baseClass: 'Positioner',
  constructor: class {
    constructor(meta) {
      callSuper(this, meta);
      …
    }
    layoutChildren() {
      …
    }
  }
});
```

That should work. Note that it doesn't use `extends`, because we don't know if the base class was already loaded at require time.

**Comment by ChALkeR** [comment]
Another note: I plan to shift our modules definition syntax to be a bit more declarative, that would make things a bit cleaner and would also help the compiler to create such modules from QML files.

**Comment by ChALkeR** [comment]
An example: a complete port of `Animation` element in [#261](https://github.com/qmlweb/qmlweb/pull/261/files).

**Comment by ChALkeR** [comment]
Note: with [ES Class Properties](https://github.com/jeffmo/es-class-fields-and-static-properties) proposal we can even get:
```js
registerQmlType(class {
  static module = 'QtQuick';
  static name = 'Animation';
  static versions = /.*/;
  static baseClass = 'QtQml.QtObject';

  static enums = {
    Animation: {
      Infinite: -1
    }
  };

  static properties = {
    alwaysRunToEnd: 'bool',
    loops: { type: 'int', initialValue: 1 },
    paused: 'bool',
    running: 'bool'
  };

  constructor(meta) {
    callSuper(this, meta);
  }
  restart() {
    this.stop();
    this.start();
  }
  start() {
    this.running = true;
  }
  stop() {
    this.running = false;
  }
  pause() {
    this.paused = true;
  }
  resume() {
    this.paused = false;
  }
  complete() {
    // To be overridden
    console.log('Unbound method for', this);
  }
});
```

And there is already a Babel plugin for that. I don't want to pull stage-1 stuff in, though. Let's wait until it reaches at least stage 2 or 3.

**Comment by ChALkeR** [comment]
Ok, I updated the proposal at #261, now it looks like
```js
registerQmlType({
  module: 'QtQuick',
  name: 'Animation',
  versions: /.*/,
  baseClass: 'QtQml.QtObject',
  enums: {
    Animation: {
      Infinite: -1
    }
  },
  properties: {
    alwaysRunToEnd: 'bool',
    loops: { type: 'int', initialValue: 1 },
    paused: 'bool',
    running: 'bool'
  }
}, class {
  constructor(meta) {
    callSuper(this, meta);
  }
  restart() {
    this.stop();
    this.start();
  }
  start() {
    this.running = true;
  }
  stop() {
    this.running = false;
  }
  pause() {
    this.paused = true;
  }
  resume() {
    this.paused = false;
  }
  complete() {
    // To be overridden
    console.log('Unbound method for', this);
  }
});
```

That removes one extra level of nesting when compared to https://github.com/qmlweb/qmlweb/issues/260#issuecomment-225307148 and that will require only header changes to be ported to #263.

So, my current proposal is to adopt #261 now, and port to #263 later, when [ES Static Properties](https://github.com/jeffmo/es-class-fields-and-static-properties) will be accepted as `stage-3` (or `stage-2`).

I am waiting for comments for two days and landing that, if there will be no objections.

/cc @Plaristote @akreuzkamp again.

**Comment by stephenmdangelo** [comment]
While trying to add new components outside of the scope of qt.js, I had to make callSuper and createProperty global: https://github.com/stephenmdangelo/qmlweb/commit/4034323f194a35da3c8f6f89e3eda714da2debc4

This change removes the need to export createProperty (awesome). Can we just always call callSuper before invoking the constructor? Or are there cases that we may want to change the arguments or timing of that call?

If we don't call callSuper automatically, does it make sense to add it to the scope of the constructor, so it doesn't have to be exported globally?

**Comment by ChALkeR** [comment]
> While trying to add new components outside of the scope of qt.js, I had to make callSuper and createProperty global: stephenmdangelo@4034323

See #51. Ideally, we need to export just one global object with all those methods.

> This change removes the need to export createProperty (awesome).

No, it doesn't. Sometimes, modules need to create properties at runtime — then `createProperty` would still be required. Not sure if that would be needed for external modules, though.

> Can we just always call callSuper before invoking the constructor?

Technically, we could, since we already are using dynamic function creation, but am not yet sure if that would be the best solution. Or we could pass it as an extra argument. I have to think about that a bit more, can't tell yet. Note that automatic addition of `callSuper` would still require it either being reachable through global scope or passed in a parameter.

> Or are there cases that we may want to change the arguments or timing of that call?

Of `callSuper`? No, that should be called as the very first command, with the exact same params.

> If we don't call callSuper automatically, does it make sense to add it to the scope of the constructor, so it doesn't have to be exported globally?

You mean passing it as an argument?

**Comment by stephenmdangelo** [comment]
> You mean passing it as an argument?

I'm thinking something like setting callSuper on the constructor prototype near the end of `registerQmlType`:

```
    if (typeof options.baseClass !== 'undefined') {
      inherit(options.constructor, options.baseClass);
    }
    
    options.constructor.prototype.callSuper = callSuper;
```

Then you can just call `this.callSuper` within the constructor.  Maybe even put it into `inherit`, since it's only something you would need if inheriting.

**Comment by akreuzkamp** [comment]
I must say, I didn't like the changes to the module definitions you made. The explicit write-everything-your-own way, that I had written wasn't nice, but straight forward. With some things being done automagically, things got unclear.
But I like this a lot. This is beautiful and straight-forward. :) Now I even endorse calling the super-constructor automagically. :)
And it brings module definitions into a shape, where a compiler can easily use it for semantic checks.
+1 from me. :)

**Comment by ChALkeR** [comment]
@akreuzkamp Thanks! Merging #261, then, and waiting for ES Static Properties to merge #263.

**Comment by akreuzkamp** [comment]
As it's out of scope for #271, I'll add a thought to it, here: PR #271 is currently missing QtObject. This is because QtObject has QObject as its baseClass, which is part of qtbase. Thus `baseClass` should also accept constructor functions, so we can simply write `baseClass: QObject`.
Moreover it's missing Component. Here we should do the same. That is, move the class itself to engine/ and register a small subclass as QtQml.Component.
