### ISSUE TITLE
`lib/` status

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#27]
We need to decide what to do with the `lib/` dir (which contains bundled code).

Do we keep it (and update it) or do we remove it from the repo?
If we keep it — how often do we update it? With each commit or between the releases?

Options that I see (anyone could propose any other solution):
 1. Remove `lib/` from the repo. Downsides — it would be harder to download this directly from GitHub, and I guess this will make the package unusable with Bower. I could be mistaken here, though.
 2. Update `lib/` before each release tag, with a separate commit. Downsides — `lib/` in the repo is desynced with the actual changes in the code, and this would make everyones `git status` not so pretty — there will (almost) always be uncommited changes in the `lib/` dir.
 3. Update `lib/` with each commit. Downsides — this would make merging, reverting, and every other everyday work a little more inconvenient. The work-around is to reset and rebuild it every time, but this would still break automatic merges.
 4. Remove `lib/` from the master branch (as in 1), make a separate branch (or branches if we would want to keep several of those somewhere in the future) for releases and package all releases from that branch (as in 2). Downsides — `master` would be uninstallable with Bower, but this looks better than having `master` actually install a previous version.
5. Remove `lib/` from the master branch (as in 1), make tags for each release that are not inside any branches, but in individual tags. Looks similar to 4, see a follow-up comment.

/cc @qmlweb/core

**Comment by ChALkeR** [comment]
If there are no other ideas, I vote for option 2.

**Comment by aspidites** [comment]
Another idea from a random guy:
4. Get rid of it, but include it in released tarballs. The end result would be that individuals who just want to try out the project would do so with code that is in sync with everything else that was released, and those that want bleeding edge would simply have to build the files for themselves. It also avoids the possibility of the code that is forked being out of sync with what is provided in /lib.

**Comment by henrikrudstrom** [comment]
I like random guys suggestion. Less room for confusion!

**Comment by Plaristote** [comment]
I would be in support for option 1. At least for now, because we're not ready to make ourselves available to bower users anyway.

I believe option 4 from aspidites doesn't fix the bower issue, but we could, instead of a tarball, just make a different repository to publish the releases.

**Comment by aspidites** [comment]
You could have master always refer to latest release, do development on feature branches, and have a tagged branch for each release that has the associated files (hybrid of what is now listed as 4 in the OP, my original suggestion, and @Plaristote's comments). 

In effect, you'd have the following scenarios:

1. Someone clones master -- It has everything you need in it and points to latest version of webqml
2. Someone wants to see what's being worked on and clones a feature branch. He has to build the files manually, but can rest assured that those files work with the development version he's using.
3. Someone wants to get an old version and checks out a specific version tag. She has the files needed for *that* version.
4. Someone installs from bower. We have both master and tagged releases to rely upon.

**Comment by ChALkeR** [comment]
@henrikrudstrom  @Plaristote 
I updated the options based on the @aspidites suggestion.

**Comment by ChALkeR** [comment]
## 4

`master` as in option 1 (without lib), `0.x` as follows:

```
* 1f14722 (HEAD -> 0.x, tag: v0.2.0) v0.2.0
* d533376 Do stuff
* 08c6f8b (tag: v0.1.0) v0.1.0
```

## 5

`master` as in option 1 (without lib), releases as follows:

```
* 4efae2b (HEAD -> 0.x) Even more stuff.
| * 9b3977f (tag: v0.3.0) v0.3.0
|/  
* c255e99 Do more stuff
| * 868d255 (tag: v0.2.0) v0.2.0
|/  
* fbd9570 Do stuff
| * 08c6f8b (tag: v0.1.0) v0.1.0
|/ 
```

**Comment by ChALkeR** [comment]
I personally like option 5 better.

**Comment by Plaristote** [comment]
I support option 5 as well.

**Comment by ChALkeR** [comment]
@Plaristote And yes, that means putting lib to `.gitignore` on master. But this would mean either removing it from gitignore in the release branch, or keeping a separate `.npmignore` file (which I think is better)

**Comment by aspidites** [comment]
@ChALkeR,

:+1: , Done  in #44 :-)
