### ISSUE TITLE
Text layouting issue when using Loader

### ISSUE THREAD

**Issue by hhaveri** [qmlweb/qmlweb#272]
It seems that a Text item (with wrapping enabled) gets incorrect dimensions when using a Loader. A minimal example is attached:
[test.zip](https://github.com/qmlweb/qmlweb/files/318359/test.zip)

In a bit more complex scenario where the width of the Text item is defined, the width is rendered correctly but the height of the Text item seems to follow the amount of spaces in the text regardless of the amount of wrapping. This happens at least if the source of the Loader is set later.

**Comment by ChALkeR** [comment]
Testcase source:

`main.qml`:
```qml
import QtQuick 2.0

Item {
    Loader {
        source: "Test.qml"
    }

    Test {
    }
}
```

`Test.qml`:
```qml
import QtQuick 2.0

Text {
    text: "lorem ipsum digitalis"
    wrapMode: Text.Wrap

    Rectangle {
        anchors.fill: parent
        color: "red"
        opacity: 0.2
    }
}
```

The issue is observable only for implicit size of the Loader, I presume. Setting `width` attribute to the `Loader` makes it look exactly as in Qt QML.

**Comment by hhaveri** [comment]
The issue is observable in other scenarios as well (i.e. the more complex case for which I didn't yet cook up a minimal example). I assume it might be the same issue, but might be a separate one as well.

Basically in my experimental page I have a separate qml file containing something like this inside a Column:

Text {
    anchors {
        left: parent.left
        right: parent.right
     }

    font.pixelSize: 40
    horizontalAlignment: Text.AlignHCenter
    text: "Some text with potential line breaks"
    wrapMode: Text.WordWrap
}

I use a Loader to load the component. If the source property of the Loader is initialized to directly load that component, the layouting seems to go fine. But if I then programmatically switch the source of the Loader to something else and back, then the Text item gets incorrect height. And obviously the column gets messed up.

**Comment by hhaveri** [comment]
Attached is another example. The initial text rendering is correct. But tapping the screen switches Loader source and text height becomes incorrect (indicated by the red area).
[secondtest.zip](https://github.com/qmlweb/qmlweb/files/321736/secondtest.zip)

**Comment by hhaveri** [comment]
Seems to be fixed now by commit 9a94f66.

**Comment by hhaveri** [comment]
However, there is still an issue with updating wrapping Text item height when its width changes.

Adding:
`this.widthChanged.connect(this, updateImplicit);`
to Text.js would seemto fix it at least somehow.

**Comment by ChALkeR** [comment]
@hhaveri Nice. Do you wish to file a PR or should I fix that? =)

**Comment by hhaveri** [comment]
Created a PR (my first one ever, so not sure how well it went).
