### ISSUE TITLE
Invitation to QtCon 2016

### ISSUE THREAD

**Issue by akreuzkamp** [qmlweb/qmlweb#273]
Hey guys,

In September (2st to 8th) this year, there will be a huge joint conference of KDE and Qt (and VLC and FSFE) communities in Berlin. It will consist of three days of presentations about all kinds of topics, related to Qt, QML, C++, KDE, VLC and open source communities in general. It will be followed by four days of BoF sessions with free discussions, hacking, etc. I will definitely attend and I kindly invite all of you to join. I would love to meet many of you, there. There will be no talk about QmlWeb unfortunately (I simply wouldn't find the time to prepare one), but we can easily do BoF and hacking sessions about it.

All information and the registration link can be found here: https://qtcon.org. Don't be deterred by the prices, you'll see there, the only thing that is with cost, is the optional training day, that is offered by KDAB on Sept, 1st. The conference itself is free for contributors/community members (and you are community members, just as I am).

If you want to join, but have financial concerns, please get in touch with me or the KDE e.V. board directly, as you might get travel cost reimbursement from the KDE e.V. (see https://ev.kde.org/rules/reimbursement_policy.php for more info). It would be a pitty if anyone could not join because of financial reasons.

I'm looking forward to seeing you in Berlin :)

PS: You're invited no matter if you're contributing a lot to QmlWeb already, just a little bit or just want to start contributing. Come and meet us :)

**Comment by Murazaki** [comment]
I, too, would like to attend the QtCon, but I guess I can't be eligible for a reimbursement ^^ (Sorry, i'm out -> [])

**Comment by ChALkeR** [comment]
I would love to attend, but I won't be able to make it this year, for personal reasons (not financial, so reimbursement won't be able to fix that). Sorry :disappointed:.

**Comment by ChALkeR** [comment]
I suppose that the event has already ended, hence closing this.

Note: I wasn't able to travel to conferences in Q3-Q4 2016 for personal reasons, but I expect that I could be able to make it next year (2017) =).

**Comment by machinekoder** [comment]
QtCon 2016 was great. I can only recommend you to visit it next year.
