### ISSUE TITLE
Component support

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#282]
Atm this code:

``` qml
import QtQuick 2.0

Rectangle {
  width: 100
  height: 100

  Component {
    id: delegate

    Rectangle {
    }
  }
}
```

throws a `Cannot assign to unexistant default property` error.

This should be fixed.

**Comment by Plaristote** [comment]
It's been fixed in f98aaa76e54d3e6a222e7a3ce5960568dca0c668
