### ISSUE TITLE
Review your names and email in AUTHORS

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#30]
@qmlweb/collaborators — please review your names and the _main_ emails in the [AUTHORS](https://github.com/qmlweb/qmlweb/blob/master/AUTHORS) file. Additional emails could be added later in a separate file, if required.

Those would be also used in the «Reviewed-By» header field of commits that you review.

Specifically, @Plaristote, what should be used as the main email?
This blocks #25 landing =).

**Comment by ChALkeR** [comment]
Open PRs to fix things or comment here if everything is ok, please =).

**Comment by Plaristote** [comment]
I'd like to use this identity:
Michael Martin Moro <michael@unetresgrossebite.com>

**Comment by ChALkeR** [comment]
@Plaristote Done in #33. Anyone else?
I'm planning on keeping this open for some time or until everyone leaves a comment here.

**Comment by ChALkeR** [comment]
Ok, I think this should be fine now and safe to close.
