### ISSUE TITLE
Eliminate private cross-file variables and methods

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#310]
Everything should be publically accessible to allow extending, as mentioned by @stephenmdangelo (btw, you could post some links here, I don't remember them atm).

That would mean that each file should either call methods of the `QmlWeb` object or add properties to the `QmlWeb` object directly, but not use local properties defined in other files.

We could enforce that with [no-undef](http://eslint.org/docs/rules/no-undef) and [no-unused-vars](http://eslint.org/docs/rules/no-unused-vard) rules, adding only one exception for the `QmlWeb` variable (browser globals would be added to exceptions list automatically after we select the browser enviroment.

Btw, those two rules are also helpful for finding other errors.

/cc @stephenmdangelo @qmlweb/core

**Comment by stephenmdangelo** [comment]
Would things like `importContextIds` and `perImportContextConstructors` in #239 then become `QmlWeb.$perImportContextConstructors`? Is there some better way to keep things like this as truly private as they are now?

**Comment by ChALkeR** [comment]
@stephenmdangelo No, both of those are used in only one file — `qml.js`. The rule I am proposing would look like: if it's used in more that one file (i.e. is used at least once in a file other than the one where it was declared), and it's not a polyfill that overrides the local variable with the same name as the original global object (e.g. `WeakMap`) — export it.

**Comment by ChALkeR** [comment]
@stephenmdangelo, @akreuzkamp Btw, there is a [Private Fields](https://github.com/tc39/proposal-private-fields) stage-1 proposal. Once that gets raised to stage-2/3 and polyfilled, we could use that instead of local variables.

**Comment by ChALkeR** [comment]
`no-undef` actually helped me to find quite a few errors: https://github.com/qmlweb/qmlweb/commit/feb22c229e7a6681f3f5aed9e48a7b284803d4fb.

Some of those were introduced by me while cleaning things up, some of those were quite old (e.g. `demoVideo` instead of `domVideo` :wink:).

**Comment by ChALkeR** [comment]
Ah — we could rename things to privatish later, e.g. `QmlWeb.executionContext` to `QmlWeb.$executionContext` or `QmlWeb._executionContext`. The main idea atm is to cleanup the code first and get all the eslint rules working.

**Comment by ChALkeR** [comment]
This is mostly done, only the following are left:
 * `registerQmlType`
 * `createProperty`
 * `callSuper`
 * `constructors` — see #331
 * `Easing`

The actual list is placed in https://github.com/qmlweb/qmlweb/blob/master/src/.eslintrc#L3
