### ISSUE TITLE
Minimal example missing

### ISSUE THREAD

**Issue by machinekoder** [qmlweb/qmlweb#343]
Can you please create a minimal example with gulp, express and qmlweb in place.

For me as non-web but experienced Qt/QML developer it is really hard to get started with qmlweb at the moment.

**Comment by machinekoder** [comment]
Found this "guide" here: https://github.com/JoshuaKolden/qmlwebtest

**Comment by ChALkeR** [comment]
@machinekoder Hi!

Express and gulp are not required for running qmlweb.

Express is server-side, gulp is a task runner (as `make`, but with streams in mind), and qmweb is a client-side library that could be served from any server (including Apache or nginx), without JS on the server-side.

A separate library exists, https://github.com/qmlweb/gulp-qmlweb — needed to pre-parse `*.qml` files (mainly to speed up loading time), but qmlweb can function without pre-parsing and with directly loading `*.qml` files. Note that `gulp-qmlweb` also doesn't have to run on the server, it could be used from the developer computer to build the assets one — so the server could still be anything that serves static files.


As for the usage on the client side, if the [Readme](https://github.com/qmlweb/qmlweb#how-to-use) is not clear enough, I will add two example pages to <https://qmlweb.github.io> soon — full-window size and embedding into a `<div>` element.

**Comment by machinekoder** [comment]
@ChALkeR Hi,

Thank you for the answer. A clear and straightforward hello world in the README would be fantastic.

**Comment by machinekoder** [comment]
Finally got it running. Just used the `qt.js` from the release and spawned express for serving the files.

Looks good for a start!

**Comment by machinekoder** [comment]
@ChALkeR I found the documentation for extending QmlWeb: https://github.com/qmlweb/qmlweb/blob/master/docs/Extending.md
Where do I have to place the libraries? Can I specify additional import/search paths for the QtQuick modules?

**Comment by Plaristote** [comment]
`registerQmlType` is just a regular javascript function, intended for use outside of the QML context. I'm assuming you're working with a web browser, so that just means you need to include your scripts like this:

```
<script type="text/javascript" src="qt.js"></script>
<script>
  registerQmlType({
    // insert code here
  });
</script>
```

If you're using the `data-qml` attribute (as shown right there: https://github.com/qmlweb/qmlweb#auto-load), you need to make sure the calls to `registerQmlType` happen before the `load` event is fired (http://www.w3schools.com/jsref/event_onload.asp), since that's when the auto-loader kicks in.

As for specifying additional import/search paths for modules, we have the `addImportPath` method (http://doc.qt.io/qt-5/qqmlengine.html#addImportPath). I'm not entirely sure how you'd get the instance to the QMLEngine though. @ChALkeR would probably know.

**Comment by machinekoder** [comment]
@Plaristote Thank you for your help.

However, I still get `import.js:67 GET http://localhost:3000/qml/MyModule/qmldir 404 (Not Found`

Any ideas?

**Comment by Plaristote** [comment]
I'm pretty sure this behavior is expected. Your import paths may include a qmldir file (as described in http://doc.qt.io/qt-5/qtqml-modules-qmldir.html), and we have to try and fetch it to know if it exists or not.

Whatever you do, these queries are going to happen, and they'll answer with 404 unless you write a qmldir file.

**Comment by machinekoder** [comment]
@Plaristote The error is confusing but seems to work.

Now I get following error from my component:
```
AwesomeItem.js:19Uncaught ReferenceError: QmlWeb is not defined
```
How can I register the QmlWeb namespace?

**Comment by ChALkeR** [comment]
@machinekoder The API changed between [v0.1.0](https://github.com/qmlweb/qmlweb/tree/v0.1.0) that you are probably used and the current `master` which would be v0.2.0 soon.

You should either use v0.1.0 API (probably not recommended if you don't want to rewrite things), or wait for 0.2.0 or 0.2.0 pre-release.

**Comment by machinekoder** [comment]
Yes, I used the version from NPM which is probably v0.1.0. I will try it again with the current master.

**Comment by machinekoder** [comment]
@ChALkeR Got one step further with the current master. I am now stuck at loading the component: `qt.js:15 Uncaught TypeError: Cannot call a class as a function`

I guess I am missing some kind of transpiler step?

**Comment by machinekoder** [comment]
Moved the AwesomeItem to the qmlweb repository and got it working. Great work so far!

I have found following problems (which you probably already about):
* No `Binding` Component
* MouseArea has no `pressed` and `released` signals
* No `readonly` property keyword

Can you give me some hints how to add these features?

**Comment by machinekoder** [comment]
@ChALkeR @stephenmdangelo 
I have a question regarding `Singletons`. Does QmlWeb currently support singletons? If not, how can I add support for singletons?

Secondly, is there a way to add QML files to the QmlWeb modules? I would require this to create a system-wide QML module and to combine it with QML components defined in JavaScript.

**Comment by ChALkeR** [comment]
Minimal usage example added in  d572d4197ae838694aadd2b0913e17d05da2f2a6.

@machinekoder 
As for `Singletons` — no, I don't think we have that yet.
To support those, first we need to be able to parse those in `qmlweb-parser`, ref: https://github.com/qmlweb/qmlweb-parser/issues/27 (btw, that was the correct place for now).
