### ISSUE TITLE
property with name "property" does not update

### ISSUE THREAD

**Issue by machinekoder** [qmlweb/qmlweb#346]
I try to implement the `Binding` QML object. Unfortunately, it has a property named `property`. Although creating a component with such a property does not cause any error, the property does not seem to update from QML.

e.g.
``` qml
Binding { target: button0; property: "checked"; value: button0Pin.value }
```
does not result in the property `property` getting the value "checked".

I suspect the QML parser is not differentiating between the `property` keyword and property names causes this problem. Can someone please give me a hint where to look at to fix this issue.

EDIT: Workaround is, of course, changing the property name. However, this breaks compatibility with desktop QML.

**Comment by stephenmdangelo** [comment]
The parser code lives here: https://github.com/qmlweb/qmlweb-parser

Probably in api.js is where it's parsing the "property" keyword. Probably need to add support for ":" following "property" vs only expecting a "name" token.
