### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by jhihn** [qmlweb/qmlweb#360]
I'm just wondering what the timeline looks like for reaching 0.2.0 and subsequent releases?

Is there a burn-down list to 0.2.0 and others?

**Comment by ChALkeR** [comment]
@jhihn See https://github.com/qmlweb/qmlweb/milestones for the list.

There is no specific release dates set.

0.2.0 is on the way and should be ready in a few days, I just need to take another look on the hanging PRs that don't have a target.
