### ISSUE TITLE
Js library file name

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#380]
Currently, the file is named `qt.js`, which is confusing.
I propose to rename it to `qmlweb.js` rather earlier than later, as this is a breaking change and I expect that the userbase in the near future will only increase (I don't expect it decreasng).

Also, I think that we should also provide non-transplited (or less-transplited) files for browsers that support ECMAScript 2015 (approx. anything except for IE11) in addition to the currently provided files. If we decide to do that, we should decide the naming for ECMAScript 2015 (aka es6) files.

We could use `qmlweb.es2015.js` and `qmlweb.parser.es2015.js`, for example. See also https://github.com/qmlweb/qmlweb/pull/378#issuecomment-269741339. 

/cc @qmlweb/collaborators,  thoughts?

**Comment by stephenmdangelo** [comment]
I'm good with those name changes. Makes more sense than "qt".

**Comment by ChALkeR** [comment]
`qmlweb.es2015.js` is out of scope here, see #395 for that.

For 0.3.0, the `./lib/` directory will have two variants — `qt.js` and `qmlweb.js`, those will be identical.
Later, `qt.js` will be removed.
