### ISSUE TITLE
Add authors to the org

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#4]
All collaborators should be probably asked to join to the org.
Will prepare a list a bit later, should be based on #3.

**Comment by ChALkeR** [comment]
The reasoning here is that the current situation with a lot of forks at various states and almost all of them being quite old and not actively worked on saddens me. Hence I wanted to bring everyone into one org, which would be governed by the collaborators.

**Comment by henrikrudstrom** [comment]
Great initiative, not much to see in my fork, but i hope to be able to contribute here!

**Comment by ChALkeR** [comment]
Everyone, there are two teams — Core (@qmlweb/core) and Collaborators (@qmlweb/collaborators).

The aim is to have functional code review (each commit is reviewed by at least one other Collaborator), but that could happen not so soon as I hope it would.

The decision making would be consensus-seeking, first among all Collaborators, and if that fails — among the Core team.

These people are invited to the Core team:
 * @lpaimen
 * @akreuzkamp 
 * @Plaristote 
 * @arnopaehler

These people are invited to the Collaborators team:
 * @labsin 
 * @Somsubhra 
 * @henrikrudstrom 
 * @JoshuaKolden 

Ping me here to get the actual org invitation

**Comment by lpaimen** [comment]
Good initiative! I've seen a lot of forks which tells me people find Qmlweb useful or at least want to tinker with it. Having a single "effort" makes it much smoother. I'm happy you picked this up!

**Comment by labsin** [comment]
Yes, I was also disappointed that there were only dead forks at the time. But I also had some fundamental issues with the program. I tried to start from scratch (not released) but also gave up.

**Comment by ChALkeR** [comment]
@labsin I agree that there are issues, but I think that it would be possible to do a gradual rewrite without starting from scratch.

**Comment by Plaristote** [comment]
Thanks for the initiative of organizing us and all the work put towards integrating our respective repositories. I'll gladly accept the invitation. I'm always eager to work on this project, I see a lot of potential in it.

I'll check what I can do to help merging everyone's work here. It's very exciting to see everyone's work, even more-so when I see all that's already been merged.

**Comment by akreuzkamp** [comment]
Hey Chalker,
thanks a lot for picking this up again! :)

I tried to pull us all together once, but failed, so I'm very glad to see you having more success.

A few weeks ago, I started to merge all my work into Plaristote's fork (locally still), because I think it's superior to mine. Please add me as a member to the org, so I can contribute the merge. :)

**Comment by ChALkeR** [comment]
Thanks, @akreuzkamp, I missed those two people.
I would have invited @pavelvasev to the `Core` team, if I would have found his fork earlier, but I think we should ask for opinions now.

@qmlweb/core, any objections to inviting @pavelvasev to the `Core` team?

**Comment by ChALkeR** [comment]
ping =)

**Comment by akreuzkamp** [comment]
No objections from my side, I strongly encourage it! :)

**Comment by ChALkeR** [comment]
@akreuzkamp Thanks! As there were no objections, I'm doing it.

Also inviting @jangmarker to the Collaborators team.

**Comment by ChALkeR** [comment]
Closing this for now.

Indivudual issues could be opened later for inviting new collaborators.
