### ISSUE TITLE
pureqml vs qmlweb

### ISSUE THREAD

**Issue by seniorivn** [qmlweb/qmlweb#401]
https://github.com/pureqml/qmlcore/issues/36
any comments?

**Comment by ChALkeR** [comment]
That is great!
Perhaps the ideas or even the code could be shared between the two projects.

I will perhaps add a link to their project in the readme, among others (see https://github.com/qmlweb/qmlweb/issues/398#issuecomment-287621587).

The main difference that I see here is that the intent of the QmlWeb project is to reimplement QML  in HTML as is, as close as possible to the Qt QML language, to support running existing apps without any changes, while [pureqml/qmlcore](https://github.com/pureqml/qmlcore) has some differences there:
> It was designed with original QML in mind, but it's not 100% compatible and better in some aspects. The main concepts are the same though, so if you're familiar with original QML, you could start right away.

Note that our sets of tests even found some issues in the Qt QML itself, those were reported and mostly fixed.

Their approach (designing an API similar to Qt QML) might be better to getting things done now, though.

---

Now, as for the specific things:

> we do QML parsing/translation/generation ahead of time. It gives more flexibility for optimization and maintenance and ease components creation;

Atm, parsing is possible ahead of time in QmlWeb (see https://github.com/qmlweb/gulp-qmlweb), which is the most heavy part. I though about implementing a code generator that would convert the structures to js classes, but that probably won't give any mesuarable benefits compared to constructing QML classes from JSON representation on the fly. We have a second walker stage, though, and that should be eliminated.

Note that in QML it's not always possible to use only ahead-of-time compilation, as QML can load dynamic QML content and has built-in API to instantiate elements from QML code that is generated on the fly, ref: http://doc.qt.io/qt-5/qml-qtqml-qt.html#createQmlObject-method.

> we are not focused strictly on web and while web is most comprehensive, platform abstraction allow to adopt pureqml to a number of Smart TVs easily;

QmlWeb is not focused on the «web», it's focused on anything that can render HTML and has non-zero share. E.g.: Electron apps are not «web apps», strictly speaking. Smart TVs are not out of scope, any issues or pull requests regarding Smart TVs are welcome here.

> with all the respect to qmlweb guys (I actually love what they are doing), some parts of pureqml a more mature even the project is younger;

That is probably correct. I have not reviewed pureqml code, but there is a significant amount of legacy code here in QmlWeb that should be cleaned up. That is on the schedule, though I can not provide estimated dates.

> we are using pureqml in our commercial projects, not a big deal, but it means we won't give up on maintenance suddenly.

QmlWeb is a project with open governance. Anyone who does valuable contributions can be given commit access, though they are expected to file all contributions through PRs to give other contributors time for review — this results in better code quality.

Atm, there are 11 people with commit access to QmlWeb.

I believe (and I have enough evidience) that this model is more sustainable in the long term that a single-entitiy controlled project.

On the other hand, there is no on afaik that gets paid for working on QmlWeb.

I would recommend PureQML team to give more control to the community when the time comes, though.

**Comment by ChALkeR** [comment]
I believe that was covered in #402.
