### ISSUE TITLE
Update for changes in remark, remark-lint

### ISSUE THREAD

**Issue by wooorm** [qmlweb/qmlweb#412]
[`remark`](https://github.com/wooorm/remark) and [`remark-lint`](https://github.com/wooorm/remark-lint) changed a bunch since it was implemented here. Most notably, see the [`remark-lint@6.0.0`](https://github.com/wooorm/remark-lint/releases/tag/6.0.0) changelog, and the [releases for `remark`](https://github.com/wooorm/remark/releases) page to find out more.

Or, feel free to ping us on [Gitter](https://gitter.im/wooorm/remark) or me below!

Cheers 👋
Titus

**Comment by Plaristote** [comment]
I've updated remark-lint to ^9.1.0 in cbbfc285533b04d298c9e6e391d4148b75d12750. It didn't break anything as far as I can tell.
