### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by ShalokShalom** [qmlweb/qmlweb#414]
A little question that comes from a newbie: How is it possible to connect the backend code? Pure Javascript? All bindings?

So, can I use also lablqml for this? 

Thanks

**Comment by ChALkeR** [comment]
> How is it possible to connect the backend code? Pure Javascript? All bindings?

QmlWeb is executed on the client side only, the closest alternative being a QML-only desktop client.

You can use XMLHttpRequest or WebSocket API to exchange data between the client and your server.

---

Cross-compiling C++ (and ocaml) code is not currently supported, but one could try to use Emscripten for that, though some bindings would be still needed on QmlWeb side. See #398.

**Comment by ShalokShalom** [comment]
Yeah, asm and webassembly is in my mind

**Comment by ChALkeR** [comment]
@ShalokShalom I don't believe that anyone has a working demo of Emscripten+QmlWeb atm, that is something that requires further research and work. We have #398 opened for that, so let's move the discussion there (and I'm closing this as duplicate).

Feel free to correct me if I understood you incorrectly — I will reopen this then.
