### ISSUE TITLE
Current state of usability

### ISSUE THREAD

**Issue by ShalokShalom** [qmlweb/qmlweb#415]
Can you say something about the current state of usability? How far is the compatibility?
Is there any project that use qmlweb productive? Is it ready for that? 

Seems some core packages are unavailable yet:

![screenshot_20170901_103613](https://user-images.githubusercontent.com/6344099/29961923-7a1101cc-8f01-11e7-907a-226af05cc0f0.png)

**Comment by andresilvasantos** [comment]
Yes, I'm curious about it as well. I'll use qmlweb for a complex web platform. It seems good performance wise and those core packages are not critical for us. So, besides the flickering in behavior animations (we'll have to trigger the animations ourselves), this is awesome!

**Comment by andresilvasantos** [comment]
Loader component doesn't have asynchronous loading implemented yet and no caching, so if you have a Repeater with 100 Loaders inside, you're UI will block for a long time to load it. Probably requires a huge code refactory to achieve this. Is anyone working on it or knows how to point me in the right direction to implement it?

**Comment by ChALkeR** [comment]
@ShalokShalom Sorry for the delay, I was a bit absent for half a year :-/.

See the [projects](https://github.com/qmlweb/qmlweb/projects) page, that mostly documents the current state of things. Note though that that is for the `master` branch, and the version on [qmlweb.github.io](https://qmlweb.github.io) is still to be updated.

**Comment by ChALkeR** [comment]
@andresilvasantos please open individual issues for bugs ;-).

I'm going to close this issue as I think that the above link to projects answers the question here.

Feel free to ping me if you want this reopened — I will do so.

**Comment by ShalokShalom** [comment]
So, if the linked code is working in the master branch, this is solved to me. 
Can you update?
