### ISSUE TITLE
Actually add some tests

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#42]
We need tests coverage to be sure that new patches aren't breaking existing things.

**Comment by ChALkeR** [comment]
Moving to 0.1.0 milestone, we actually need tests for checking that merges are not breaking things.

**Comment by henrikrudstrom** [comment]
would like to contribute a bit to that, 
having trouble with jasmine-phantom on windows though: [see issue](https://github.com/dflynn15/gulp-jasmine-phantom/issues/53)
hopefully that will be resolved soon. 
Any thoughts on how to organize the tests?

**Comment by ChALkeR** [comment]
@henrikrudstrom I'm going to make some examples soon, and those could be used as the starting point.

**Comment by ChALkeR** [comment]
For starters, #50, #53, #54 should fix this.
Then we just need to add more tests =).

**Comment by ChALkeR** [comment]
Fixed in #50, #53, #54.
Landed in 220ff4588d50efbf867383d440c6712ed37c1838...39f12e5772d9e0db401fe72bd4ad3920630a3e07.
