### ISSUE TITLE
It's a maze Nothing works

### ISSUE THREAD

**Issue by TechComet** [qmlweb/qmlweb#421]
Hi,

It's a maze
Nothing works

Thanks...

**Comment by stephenmdangelo** [comment]
Hello,

I've successfully deployed an application using qmlweb with some minor modifications to make it more touch-friendly and support a QtQuick 1 codebase.

Are you having a particular issue?

Coming from Qt/C++ land, sorting out the world of JavaScript build tools (npm, gulp, etc.) definitely took a little getting used to and was pretty overwhelming at first.

**Comment by TechComet** [comment]
The examples not work

The fullpage.html
<!DOCTYPE html>
<html>
  <head>
    <title>QML Fullpage Auto-load Example</title>
    <script src="../lib/qmlweb.js"></script>
  </head>
  <body style="margin: 0" data-qml="qml/main.qml">
  </body>
</html>

----------------
The file "../lib/qmlweb.js" does not exist

**Comment by ae86yyk** [comment]
The npm's package isn't the newest.
You'd bertter build it by your self.
Manually (recommended if you cloned from git) — npm install && npm run build.

**Comment by TechComet** [comment]
Now it is make lib folder .. but examples not work

I'm download
qmlweb.github.io it is work

**Comment by ae86yyk** [comment]
![tim 20171013132603](https://user-images.githubusercontent.com/4171863/31531510-29c4b9fe-b01a-11e7-85fe-c5ad56e82739.png)
Does your lib folder is the same as this?

**Comment by TechComet** [comment]
Yes

**Comment by stephenmdangelo** [comment]
Are you running via a web server or the file system? If it’s the file system, your browser may be blocking the call to dynamically load the parser.

**Comment by ChALkeR** [comment]
TechComet, use the `master` version or use the Readme for [v0.2.0](https://github.com/qmlweb/qmlweb/tree/v0.2.0). Also the readme [at npm](https://www.npmjs.com/package/qmlweb) corresponds to the version published there.

And don't serve it from your filesystem — browser generally blocks file requests to local files (with a few exceptions), use e.g. `npx http-server` to run a local webserver.

I hope this answers the question here, I will close this issue. Feel free to ping me if you want this reopened!
