### ISSUE TITLE
It does not work on Win-7 64, npm 3.10.5 

### ISSUE THREAD

**Issue by AlexITMan** [qmlweb/qmlweb#423]
It does not work on Win-7 64, npm 3.10.5 

I run 

npm install qmlweb

an error occurs: no such file or directory, open my path/package.json 

and there are no files in the lib folder: 

qmlweb.js
qmlweb.js.map
qmlweb.min.js
qmlweb.min.js.map

Other files are

**Comment by ChALkeR** [comment]
@AlexITMan Those instruction is for the `master` branch. For the last published version (v0.2.0) the corresponding file were historically named `qt.js` and `qt.min.js`. See https://github.com/qmlweb/qmlweb/tree/v0.2.0

That will be changed to `qmlweb.js` once v0.3.0 will be published.

I'm closing this issue as I think that answers the question, feel free to ping me if you think that this should be reopened. :wink:
