### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by JohnBrouillet** [qmlweb/qmlweb#426]
Hi ! 
Is there a way to use the camera ? I would like to try some video processing in realtime.
Thanks.

**Comment by ChALkeR** [comment]
Not yet, but it's planned. See https://github.com/qmlweb/qmlweb/projects/54#card-7324851
There is a stub for it now, it yet has to be implemented in JS.

**Comment by ChALkeR** [comment]
Closing per the new [CONTRIBUTING.md](https://github.com/qmlweb/qmlweb/blob/master/CONTRIBUTING.md), individual element progress is tracked in [Projects](https://github.com/qmlweb/qmlweb/projects).
