### ISSUE TITLE
Example (KaOS welcome app)

### ISSUE THREAD

**Issue by ShalokShalom** [qmlweb/qmlweb#427]
I just add the main.qml of a small little greeter app: 

![screenshot_20180210_033832](https://user-images.githubusercontent.com/6344099/36057818-16107c6a-0e14-11e8-90da-dc3f1236340a.png)

Here is the source code: https://github.com/KaOSx/welcome_qml

**Comment by ChALkeR** [comment]
The first issue is this one: https://github.com/qmlweb/qmlweb-parser/issues/36

Apart from that, not all QML elements from the ones used there are supported atm.
