### ISSUE TITLE
I was not able to run example

### ISSUE THREAD

**Issue by bessorion** [qmlweb/qmlweb#432]
Hi!
I've cloned master, build it and tried to run example.
I've started simple webserver on expressjs, it just hosts static files.

My wwwroot folder contains:
- copy of example folder from repository (3 *.html and qml/main.qml)
- copy built library from lib folder (/lib/*)

When I start server and try to run example I receive next errors in browser console:

**`TypeError: Super expression must either be null or a function, not undefined
qmlweb.js:15`**
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
import.js:40`
`QMLEngine.loadComponent: Loading file: http://localhost:3000/qml/main.qml
QMLEngine.js:534`
`Loading parser...
qmlstructure.js:257`
**`TypeError: i is not a constructor[Learn More]
QMLEngine.js:207`**

Could you please help me to get started with this library

**Comment by bessorion** [comment]
I receive the same error when I try to run `npm i && npm run coverage` :
`Uncaught TypeError: Super expression must either be null or a function, not undefined at tmp/qmlweb.covered.js:125228`

**Comment by ChALkeR** [comment]
Hi! Sorry for the delayed response, looking at it.

**Comment by bessorion** [comment]
I'm so happy you've finally answered )
I'm afraid I cannot use grep on windows, so I'll attach the whole file.

[tmp.zip](https://github.com/qmlweb/qmlweb/files/1965601/tmp.zip)

C:\Users\BeSSoRioN\Documents\GitHub\qmlweb>node --version
v8.11.1

Please let me know if you need something else

**Comment by bessorion** [comment]
I searched through the file and the same initialization order I'd seen during debug procedure with firebug: some base classes was instantiated normally (plased in ./src/qtbase and ./src/engine), then QmlWeb_Dom_DomElement throws exception (why is it the first from ./src/modules ?)

**Comment by ChALkeR** [comment]
Yes, I can confirm that the order is indeed incorrect in your build.

I reproduced the build that you have, and I suppose that the error is somewhere somewhere along this line: https://github.com/qmlweb/qmlweb/blob/master/builder/shaker.js#L50, i.e. my guess would be that `relative.startsWith(prefix)` always fails on Windows. Could be caused by different path normalization, looking at it.

**Comment by ChALkeR** [comment]
Try replacing this
```
    if (relative.startsWith(prefix) && relative !== QtGlobal) {
      const filename = path.relative(path.join(root, prefix), file.path);
```
with this:
```
    if (relative.startsWith(prefix) && relative !== QtGlobal) {
      const filename = path.relative(path.join(root, prefix), file.path);
```
```
    const filename = path.relative(path.join(root, prefix), file.path);
    if (!filename.startsWith("..") && relative !== QtGlobal) {
```

**Comment by ChALkeR** [comment]
@bessorion See #433.
Try testing `windows-shaker` branch — check it out, `lib` and `tmp` dirs (just in case) and re-run.
