### ISSUE TITLE
qml text in rectangle position bug

### ISSUE THREAD

**Issue by t2dk49580** [qmlweb/qmlweb#442]
Rectangle {
        id: rectangle1
        color: "#ffffff"
        anchors.bottom: rectangle.top
        anchors.bottomMargin: 0
        anchors.top: parent.top
        anchors.topMargin: 0
        anchors.right: parent.right
        anchors.rightMargin: 0
        anchors.left: parent.left
        anchors.leftMargin: 0

        Text {
            id: text1
            text: qsTr("0.1")
            anchors.fill: parent
            verticalAlignment: Text.AlignVCenter
            horizontalAlignment: Text.AlignHCenter
            font.pixelSize: 12
        }
    }

0.1 always on screen top but it is on screen middle in Qt creator

**Comment by wian007** [comment]
This is because verticalAlignment is not implemented on the Text object.

**Comment by ChALkeR** [comment]
Seems to be fixed by #444. Feel free to let me know if it's not fixed — I'll reopen the issue then.
