### ISSUE TITLE
ability to import external libraries

### ISSUE THREAD

**Issue by mathieujobin** [qmlweb/qmlweb#449]
would you know how I could be importing external libraries... such as...

```
import QtQuick 2.0
import org.kde.kwin.decoration 0.1
import org.kde.kwin.decorations.plastik 1.0
```

thanks

**Comment by Plaristote** [comment]
You would need to write qmlweb bindings for such imports. You would also need to re-implement the libraries themselves, especially if it includes any C++ parts, which would need to be re-written in JavaScript.

**Comment by mathieujobin** [comment]
Thanks for your reply.

Could these bindings be be generated using a tool like Smoke ? or nbind?

**Comment by Plaristote** [comment]
I strongly doubt it: QmlWeb isn't really Qml, it's a complete re-write that mimicks Qml using HTML, CSS and JavaScript.
At the very least, it wouldn't work right out of the box.

**Comment by mathieujobin** [comment]
Thank you, that make sense...
