### ISSUE TITLE
Merge and commit landing process

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#46]
### How the merge process goes.

Key points:
1. The commits should have `PR-URL`, `Reviewed-By`, and (sometimes) `Fixes` fields.
2. `PR-URL` and `Fixes` should be full links to relevant GitHub PR and Issues accordingly.
3. Fast-forward is preferred instead of merges to reduce commit noise. **Edit:** I'm not sure about this, especially for the PRs with many commits, and perhaps we should discuss this =).
4. This is lower priority, but if possible — we should get nice badges at the PRs to make it clear that those were merged.
5. The Travis CI checks should pass.
6. AUTHORS should contain a full list of all contributors.

How to achieve this:
1. Rebase the commits that you are merging against current master.
2. Add header fields (`PR-URL`, `Reviewed-By`, `Fixes`) to them.
   
   This and step 1 could be done together, using `git rebase -i master` and marking all commits with an `e` to amend them.
3. If possibble — force-push to the branch that is being merged, this way the PR will be marked as `Merged` afterwards.
4. Wait around two minutes for Travis CI tests to complete and make sure that those are green.
   
   _Note to self:_ I was not waiting for them at this point, and this is why we got red Travis statuses on the closed pull requests, because the merge itself failed.
5. Land the commits on `master` and push.

/cc @qmlweb/collaborators

**Comment by ChALkeR** [comment]
GitHub is not very good at this, afaik the «rebase» button is one of the most wanted features here.

**Comment by henrikrudstrom** [comment]
found this: https://github.com/git-land/git-land 
regarding 3. found this in their docs:

> If merging a PR, append [close #<PR number>] to the last commit message so that Github will close the pull request when the merged commits are pushed.

**Comment by ChALkeR** [comment]
A status update: GitHub added «squash and merge» option, so just using that for indivudual commits is fine, as long as you add the `PR-URL` and `Reviewed-By` information at the merge time (which could be added thought GitHub web ui).

I used that for merging #250, for example.

**Comment by ChALkeR** [comment]
I guess I will just close this, enforcing the hard rules here just adds churn, «Rebase and merge» is now good enough. Will think about it more if there would be any issues with that.

**Comment by ChALkeR** [comment]
@qmlweb/collaborators, I abolished the previous pr review process, so feel free to fix/commit/accept PRs on your own judgment. Waiting for reviews on complex and/or controversial things would still be good, but again — on your own judgment ;-). Given what I observed now, it would be easier for us to fix things later than to being idle and doing nothing here.
