### ISSUE TITLE
How can I load a project instead of a single qml file？

### ISSUE THREAD

**Issue by Martin-Rao** [qmlweb/qmlweb#461]
hi, How can I load a project instead of a single qml file？thanks.

**Comment by Plaristote** [comment]
You should be able to load other QML files using `import`.

But in my opinion, the best way to handle a QML project is to use a [Qt resource file](https://doc.qt.io/qt-5/resources.html) in conjonction with [gulp-qmlweb](https://github.com/qmlweb/gulp-qmlweb).
