### ISSUE TITLE
Remove `global` usage

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#51]
This should be probably done after merges.

Instead of using global, everything should be added to a single object (`qmlweb`? `QmlWeb`? `QMLWeb`? `QML`?) and that object should be added as a `window` property on browsers or directly exported in CJS.

This will allow us to ditch `encapsulate.begin.js` and `encapsulate.end.js` files which are actually not js files and make the build process simplier.

**Comment by ChALkeR** [comment]
This should be also a step to fix #41.

**Comment by ChALkeR** [comment]
`encapsulate.begin.js`/`encapsulate.end.js` were already removed, but the `global` is still used.
I'm keeping this open until that is fixed.

**Comment by akreuzkamp** [comment]
I'm for `QmlWeb` this is common naming for namespaces. :)

**Comment by ChALkeR** [comment]
@akreuzkamp See #285 =).
