### ISSUE TITLE
git instructions on wiki page

### ISSUE THREAD

**Issue by henrikrudstrom** [qmlweb/qmlweb#85]
collected all the git instructions from the comments and created a wiki page; https://github.com/qmlweb/qmlweb/wiki/Contribute-Code

@ChALkeR could you please see if this is correct?

also added some links that describes the general workflow, if anyone has a better/shorter link please suggest it.

Would be good to have a section on when to rebase and when to merge (ff-only or no-ff)
does this make sense to us: http://emmajane.github.io/rebasing-workflow/#/0/26

**Comment by ChALkeR** [comment]
Perhaps we should also create a `CONTRIBUTING.md` file?

**Comment by henrikrudstrom** [comment]
thats a good idea.

**Comment by ChALkeR** [comment]
GitHub "Rebase and merge" is good now, and I decided to remove the complexity with `Reviewed-By` etc.
Closing for now, will reopen if any issues arise.
