### ISSUE TITLE
TextInput does not follow its height property

### ISSUE THREAD

**Issue by travellhyne** [qmlweb/qmlweb#90]
The internal input element does not seem to follow the height of its container. It also overflows from the container.

 Setting the input to have a 100% height and `box-sizing` to `border-box` might be able to fix this.

**Without `{height: 100%; box-sizing: border-box;}`**
![image](https://cloud.githubusercontent.com/assets/1308095/13452163/805316f0-e080-11e5-8fd8-377a0a464387.png)

**With `{height: 100%; box-sizing: border-box;}`**
![image](https://cloud.githubusercontent.com/assets/1308095/13452191/af4ce8a0-e080-11e5-9777-dbc2e24d7198.png)

**Comment by henrikrudstrom** [comment]
there seems to be other components that miss "box-sizing" see #72

**Comment by Plaristote** [comment]
Considering the ways border work in QML, I assume `border-box` should be set for every element within a QML web page.
It's perhaps something that we shouldn't fix within TextInput or BorderImage, but set globally. Perhaps by using a stylesheet.

**Comment by ChALkeR** [comment]
@Plaristote has a valid point here, perhaps we should add a «qml» class and assign it on all items (or just the root item). I do not think that we should change the _default_ behaviour, because one could mix qml and html.

But let's for now just set the styles manually as a quick fix, and discuss the addition of a css file separately.

**Comment by ChALkeR** [comment]
@travellhyne Could you also provide a QML testcase, please?

**Comment by ChALkeR** [comment]
Status update: c9a3d27 by @igosoft should fix the height (not yet merged), and we are discussing at #110 the best way to apply `box-sizing: border-box` to everything QML by default.

**Comment by ChALkeR** [comment]
`box-sizing` part is at #120.

**Comment by ChALkeR** [comment]
The `height` part is at #122.

**Comment by ChALkeR** [comment]
@travellhyne, this should be fixed in [v0.0.7](https://github.com/qmlweb/qmlweb/releases/tag/v0.0.7).

I'm closing this now, feel free to ask for reopen if this wasn't fixed somewhy.
